import { Varela_Round } from "next/font/google";

import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const varela = Varela_Round({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--varela-font",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={varela.variable}>
        <Header />
        <main className="py-24 container text">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
